# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'IOSPOC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOSPOC

pod 'Firebase'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Fabric', '~> 1.7.11'
pod 'Crashlytics', '~> 3.10.7'

  target 'IOSPOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOSPOCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
